services:
  - type: web
    name: deejohnson-logistics
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: true